default:
  filenames:
    contracts: "contracts.xlsx"
    convert_bank_extract_save: "output.xlsx"
    convert_bank_extract_source: "data.csv"
    sales_and_vat: "sales_and_vat.xlsx"
  rel_paths:
    bookkeeping: "bookkeeping/"
    dropbox:
      ians_macbook_pro_local: "../../../Dropbox/"
prod:
  rel_paths:
    livecorp: "F3Mmedia/Internal/ACcounts/LiveCorp/"
    save_files: "run_results/"
    source_files: "source_files/"
test:
  rel_paths:
    livecorp: "spec/support/test_files/"
    save_files: "spec/support/test_files/"
    source_files: "spec/support/test_files/"
