default:
  bookkeeping_path: "bookkeeping/"
  contracts_filename: "contracts.xlsx"
  sales_and_vat_filename: "sales_and_vat.xlsx"
  dropbox_path:
    ians_macbook_pro_local:
      rel_livecorp_path: "../../../Dropbox/"
prod:
  rel_livecorp_path: "F3Mmedia/Internal/ACcounts/LiveCorp/"
test:
  rel_livecorp_path: "spec/support/source_test_files/"